BoutiqueVehicles = {
    {label = 'T-Max', model = 'tmax', description = nil, price = 500},
    {label = 'Ninja H2', model = 'ninjah2', description = nil, price = 950},
    {label = 'Dodge Challenger', model = '16challenger', description = nil, price = 1500},
    {label = 'Toyota Supra', model = 'a80', description = nil, price = 2000},
    {label = 'Lamborghini Venatus', model = 'venatus', description = nil, price = 2500},
    {label = 'Mercedes GT63', model = 'rmodgt63', description = nil, price = 2500},
    {label = 'Bugatti Divo', model = 'rmodbugatti', description = nil, price = 1645},
    {label = 'Dodge Charger 69', model = 'rmodcharger69', description = nil, price = 1645},
    {label = 'Darki 8', model = 'rmoddarki8', description = nil, price = 1645},
    {label = 'Mercedes E 63 S', model = 'rmode63s', description = nil, price = 1645},
    {label = 'Nissan GTR-50', model = 'rmodgtr50', description = nil, price = 1645},
    {label = 'Honda Xadv', model = 'xadv', description = nil, price = 1645},
 }

 BoutiqueAirPlaines = {
     {model = 'microlight', description = nil, price = 750},
     {model = 'havok', description = nil, price = 1000},
     {model = 'stunt', description = nil, price = 1250},
     {model = 'buzzard2', description = nil, price = 1500},
     {model = 'supervolito2', description = nil, price = 2000},
     {model = 'swift2', description = nil, price = 2500},
     {model = 'luxor2', description = nil, price = 3000},
 }
 
 -- BATEAUX
 
 BoutiqueBoat = {
     {model = 'Sweatyshark3', description = nil, price = 750},
     {model = 'submersible', description = nil, price = 1250},
     {model = 'submersible2', description = nil, price = 1500},
     {model = 'longfin', description = nil, price = 2000},
     {model = 'sr650fly', description = nil, price = 2500},
 }
 
 -- ARMES 
 
 WeaponBoutique = {
     {label = 'Epée en diamant', name = 'WEAPON_HATCHET', description = nil, price = 450},
     {label = 'Navy Revolver', name = 'WEAPON_NAVYREVOLVER', description = nil, price = 1500},
     {label = 'Gusenberg', name = 'WEAPON_GUSENBERG', description = nil, price = 2500},
     {label = 'Pistolet Cayo', name = 'WEAPON_GADGETPISTOL', description = nil, price = 1500},
     {label = 'AK-47', name = 'WEAPON_ASSAULTRIFLE', description = nil, price = 2500},
     {label = 'Arme de Défense Personnel', name = 'WEAPON_COMBATPDW', description = nil, price = 3500},
 }
 
 -- CAISSE MYSTERE
 
 BoutiqueMysteryBox = {
     {label = 'Caisse ~y~Rare~s~', description = 'Prix : 500 ~r~Sweaty~w~Coins', model = 'caisse_gold', rightlabel = nil, price = 500},
     {label = 'Caise ~r~Légendaire~s~', description = 'Prix : 1000 ~r~Sweaty~w~Coins', model = 'caisse_diamond', rightlabel = nil,  price = 1000},
     {label = 'Caisse ~r~Ultime~s~',description = 'Prix : 2500 ~r~Sweaty~w~Coins', model = 'caisse_ruby', rightlabel = nil,  price = 2500},
    -- {label = 'Caisse ~r~No~s~ël', description = 'Prix : 1500 ~r~Sweaty~w~Coins', model = 'caisse_noel',rightlabel = nil, price = 1500},
     --{label = 'Caisse Halloween', description = 'Prix : 1500 ~r~Sweaty~w~Coins', model = 'caisse_halloween',rightlabel = nil, price = 1500},
    -- {label = 'Caisse Fidelité', description = 'Obtenable uniquement via le Bonus Fidélité', model = 'caisse_fidelite',rightlabel = nil, price = 9999999},
     --{label = 'Caisse Véhicule',description = 'Prix : 1750 ~r~Sweaty~w~Coins', model = 'caisse_vehicule', rightlabel = nil,  price = 1750}
 }
 
 VisualitionCaisse = {
     ['caisse_gold'] = {
         {model = 'weapon_pistol_mk2', label = 'Pistolet MK2', rarity = 4},
         {model = 'Coins_1000', label = '1000 Coins', rarity = 4},
         {model = 'weapon_machinepistol', label = 'Pistolet Mitrailleur', rarity = 3},
         {model = 'weapon_katana', label = 'Katana', rarity = 3},
         {model = 'money_150000', label = '150000$', rarity = 2},
         {model = 'money_250000', label = '250000$', rarity = 2},
         {model = 'money_500000', label = '500000$', rarity = 2},
         {model = 'ferrari812', label = 'Ferrari 812', rarity = 2},
         {model = 'gadget_parachute', label = 'Parachute', rarity = 1},
         {model = 'a45amg', label = 'a45amg', rarity = 1},
         {model = 'm6prior', label = 'BMW M6', rarity = 1},
         {model = 'bmci', label = 'BMW M5', rarity = 1},
         {model = 'weapon_stone_hatchet', label = 'Hache en bois', rarity = 1},
     },
     ['caisse_diamond'] = {
         {model = 'weapon_pumpshotgun', label = 'Fusil a pompe', rarity = 4},
         {model = 'weapon_heavyshotgun', label = 'Fusil a Pompe', rarity = 4},
         {model = 'weapon_appistol', label = 'Pistolet Perforant', rarity = 3},
         {model = 'weapon_assaultrifle', label = 'Fusil d\'assault', rarity = 3},
         {model = 'money_1000000', label = '1000000$', rarity = 2},
         {model = 'Coins_850', label = '850 Coins', rarity = 2},
         {model = 'Coins_500', label = '500 Coins', rarity = 2},
         {model = 'rmod918spyder', label = 'Porshe 918 Spyder', rarity = 1},
         {model = 'rmodc63amg', label = 'Mercedes AMG C63', rarity = 1},
         {model = 'rmodchiron300', label = 'Bugatti Chiron', rarity = 1},
         {model = 'rmodatlantic', label = 'Bugatti Atlantic', rarity = 1},
         {model = 'rs615', label = 'Audi RS6 2015', rarity = 1},
         {model = 'rs7r', label = 'Audi RS7 R', rarity = 1},
         {model = 'rmod240sx', label = 'Voiture de Drift', rarity = 1},
         {model = 'nh2r', label = 'Moto', rarity = 1},
         {model = 'g65amg', label = 'Mecedes G65 AMG', rarity = 1},
         {model = 'rmodpagani', label = 'Pagani', rarity = 1},
         {model = 'rmodr8c', label = 'Audi R8 C', rarity = 1},
         {model = 'rs318', label = 'Audi RS3 2018', rarity = 1},
         {model = 'km1000rr', label = 'Moto', rarity = 1},
         {model = 'rmodrover', label = 'Range Rover', rarity = 1},
         {model = '760m', label = 'BMW 760M', rarity = 1},
         {model = 'rmodg65', label = 'Brabus 500', rarity = 1},
         {model = 'brabus800', label = 'Brabus 800', rarity = 1},
     },
     ['caisse_ruby'] = {
         --{model = 'weapon_combatmg_mk2', label = 'Mitrailleuse de Combat MK2', rarity = 4},
         --{model = 'weapon_mg', label = 'Mitailleuse', rarity = 4},
         --{model = 'weapon_combatmg', label = 'Mitrailleuse de Combat', rarity = 4},
         --{model = 'weapon_marksmanrifle_mk2', label = 'Fusil Marskman', rarity = 4},
         {model = 'weapon_assaultshotgun', label = 'Fusil a pompe d\'assault', rarity = 4},
         {model = 'swift2', label = 'Helicoptère de luxe', rarity = 4},
         {model = 'weapon_heavysniper_mk2', label = 'Fusil Sniper Heavy', rarity = 4},
         {model = 'cargobob2', label = 'Cargobob', rarity = 4},
         {model = 'gls632', label = 'GLS 63 Blinder', rarity = 4},
 
         {model = 'luxor2', label = 'Avion de Luxe', rarity = 3},
         {model = 'buzzard2', label = 'Buzzard', rarity = 3},
         {model = 'avenger', label = 'Avenger', rarity = 3},
         
         {model = 'Coins_800', label = '800 Coins', rarity = 1},
         {model = 'Coins_850', label = '850 Coins', rarity = 1},
         {model = 'Coins_1000', label = '1000 Coins', rarity = 1},
         {model = 's1000rr', label = 'Moto', rarity = 1},
         {model = 'p1', label = 'Mclaren P1', rarity = 1},
         {model = 'rs6abtp', label = 'Audi RS6 ABT', rarity = 1},
         {model = 'rs615', label = 'Audi RS6', rarity = 1},
     },
     ['caisse_noel'] = {
        {model = 'WEAPON_SCAR17FM', label = 'SCAR 17', rarity = 4},
        {model = 'Coins_2250', label = '2250 ~r~Sweaty~s~Coins', rarity = 4},
        {model = 'WEAPON_SPECIALCARBINE', label = 'Carabine Spéciale', rarity = 4},
        {model = 'WEAPON_COMBATPDW', label = 'ADP de Combat', rarity = 4},
        {model = 'vehicleunique', label = 'Véhicule Unique ( 75€ )', rarity = 4},
        {model = 'cargobob2', label = 'Cargobob', rarity = 4},
        {model = 'gls632', label = 'GLS 63 Blinder', rarity = 4},
        {model = 'WEAPON_ASSAULTRIFLE', label = 'Fusil d\'assault', rarity = 3},
        {model = 'WEAPON_GADGETPISTOL', label = 'Pistolet Cayo', rarity = 3},
        {model = 'WEAPON_SNOWBALL', label = 'Boule de neige', rarity = 3},
        {model = 'Custom_5', label = 'Jeton Custom x5', rarity = 3},
        {model = 'q820', label = 'Audi Q8 2020', rarity = 2},
        {model = 'Custom_3', label = 'Jeton Custom x3', rarity = 2},
        {model = 'WEAPON_CASABLANCA', label = 'Machete Casa Blanca', rarity = 2},
        {model = 'WEAPON_KATANA', label = 'Katana', rarity = 2},
        {model = 'Custom_1', label = 'Jeton Custom x1', rarity = 1},
        {model = 'mb250', label = 'Van Mercedes V250', rarity = 1},
        {model = 'GADGET_PARACHUTE', label = 'Parachute', rarity = 1},
        {model = 'survolt', label = 'Citroën Survolt', rarity = 1},
        {model = 'senna', label = 'McLaren Senna', rarity = 1},
        {model = 'rmodm5e34', label = 'BMW M5 E34', rarity = 1},
        {model = 'acz4', label = 'BMW Z4', rarity = 1},
        {model = 'a80', label = 'Toyota Supra', rarity = 1},
        {model = 'rmodrs6', label = 'AUDI RS5', rarity = 1},
        {model = '16challenger', label = 'Dodge Challenger', rarity = 1},
        {model = 'r820', label = 'AUDI R8 2020', rarity = 1},
        {model = 'rmodx6', label = 'BMW X6 M', rarity = 1},
     },
     ['caisse_halloween'] = {
         {model = 'dune2', label = 'Voiture Halloween', rarity = 3},
         {model = 'SweatyCoins_2500', label = '2500 ~r~Sweaty~w~Coins', rarity = 3},
         {model = 'speedo2', label = 'Camion Halloween', rarity = 3},
         {model = 'weapon_flaregun', label = 'Flare Gun', rarity = 2},
         {model = 'money_2500000', label = '2500000$', rarity = 2},
         {model = 'money_1500000', label = '1500000$', rarity = 2},
         {model = 'BType2', label = 'BType 2', rarity = 1},
         {model = 'money_750000', label = '750000$', rarity = 1},
         {model = 'Tornado6', label = 'Tornado Halloween', rarity = 1},
     },
     ['caisse_fidelite'] = {
         --{model = 'weapon_combatmg_mk2', label = 'Mitrailleuse de Combat MK2', rarity = 4},
         --{model = 'weapon_mg', label = 'Mitailleuse', rarity = 4},
         --{model = 'weapon_combatmg', label = 'Mitrailleuse de Combat', rarity = 4},
         {model = 'weapon_assaultshotgun', label = 'Fusil a pompe d\'assault', rarity = 4},
         {model = 'weapon_marksmanrifle_mk2', label = 'Fusil Marskman', rarity = 4},
         {model = 'swift2', label = 'Helicoptère de luxe', rarity = 4},
         {model = 'weapon_heavysniper_mk2', label = 'Fusil Sniper Heavy', rarity = 4},
         {model = 'cargobob2', label = 'Cargobob', rarity = 4},
         {model = 'gls632', label = 'GLS 63 Blinder', rarity = 4},
 
         {model = 'luxor2', label = 'Avion de Luxe', rarity = 3},
         {model = 'buzzard2', label = 'Buzzard', rarity = 3},
         {model = 'avenger', label = 'Avenger', rarity = 3},
         
         {model = 'Coins_800', label = '800 Coins', rarity = 1},
         {model = 'Coins_850', label = '850 Coins', rarity = 1},
         {model = 'Coins_1000', label = '1000 Coins', rarity = 1},
         {model = 's1000rr', label = 'Moto', rarity = 1},
         {model = 'p1', label = 'Mclaren P1', rarity = 1},
         {model = 'rs6abtp', label = 'Audi RS6 ABT', rarity = 1},
         {model = 'rs615', label = 'Audi RS6', rarity = 1},
         {model = 'gadget_parachute', label = 'Parachute', rarity = 1},
     },
     ['caisse_vehicule'] = {
         {model = 'cooperworks', label = 'Cooper', rarity = 1},
         {model = 'FCT', label = 'Ferrari 2015', rarity = 3},
         {model = 'M3E30', label = 'BMW M3 E30', rarity = 2},
         {model = 'mercxclass', label = 'Mercedes-Benz X-Class', rarity = 2},
         {model = 'Mustang', label = 'Mustang', rarity = 2},
         {model = 'PEANUT', label = 'PEANUT', rarity = 1},
         {model = 'rmodmustang', label = 'Mustang GT', rarity = 3},
         {model = 'TESLAMODELS', label = 'Tesla model S', rarity = 1},
         {model = 'VIPER', label = 'VIPER', rarity = 3},
     },
 }